# Generated by Django 4.2.4 on 2023-08-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogdetailpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
