# Generated by Django 4.2.4 on 2023-08-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogdetailpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='description',
            field=models.CharField(blank=True, help_text='Blog description used in cards on blog list pages', max_length=1024, null=True),
        ),
    ]
