# Generated by Django 4.2.4 on 2023-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_banner_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
