# Generated by Django 4.2.4 on 2023-08-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_link_text',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
