# Generated by Django 4.2.4 on 2023-08-11 04:41

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_banner_link_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
