# Generated by Django 4.2.4 on 2023-08-11 06:19

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('icon_grid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=24, required=True)), ('intro_text', wagtail.blocks.CharBlock(max_length=256, required=True))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
