# Generated by Django 4.2.4 on 2023-08-11 07:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('icon_grid', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=24, required=True)), ('intro_text', wagtail.blocks.CharBlock(max_length=256, required=True)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.RichTextBlock(features=[], help_text='Paste SVG code here')), ('title', wagtail.blocks.CharBlock(max_length=24, required=True)), ('text', wagtail.blocks.CharBlock(max_length=256, required=True))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
